#Server Properties
server.port=9081


# AD server connection properties
ad.url=ldap://server-url
ad.port=389
ad.usernamePrefix=Username



ad.username=username
ad.password=password


# LDAP authentication properties
spring.ldap.base=spring.ldap.base
spring.ldap.dn=spring.ldap.dn
spring.security.ldap.user-search-base=(sAMAccountName={0})
spring.ldap.head-office-group-search-base=spring.ldap.head-office-group-search-base
spring.ldap.district-group-search-base=spring.ldap.district-group-search-base
spring.ldap.Office.365-group-search-base=spring.ldap.Office.365-group-search-base
spring.ldap.Staged.Users-group-search-base=spring.ldap.Staged.Users-group-search-base
#spring.ldap.search.base=DC=coopbank,DC=local
server.connection-timeout=600000 # Timeout in milliseconds (e.g., 60 seconds)


# Spring Boot Properties
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://database-server:5432/cbo?currentSchema=sso
spring.datasource.username=admin
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.auto=update
spring.main.allow-bean-definition-overriding=true
application.security.jwt.secret-key= 586E5A7234753778214125442A472D4B6150645367566B59703373357638792F
application.security.jwt.expiration= 30000000
application.security.jwt.refresh-token.expiration=6048000000000
#logging.level.root=DEBUG
#logging.level.org.springframework.security.ldap=DEBUG
