package com.cbo.sso.models;

public enum ERole {
    ROLE_SUPER_ADMIN,
    ROLE_EMS_ADMIN,
    ROLE_EMS_USER,
    ROLE_CC_ADMIN,
    ROLE_CC_USER,
    ROLE_CC_USER_DELIQUENT,
    ROLE_ICMS_ADMIN,
    ROLE_ICMS_DISTRICT_IC,
    ROLE_ICMS_BRANCH_IC,
    ROLE_ICMS_BRANCH_MANAGER,

    ROLE_ICMS_PROVISION,
    ROLE_SASV_ADMIN,
    ROLE_SASV_USER,
    ROLE_MEMO_ADMIN,
    ROLE_MEMO_USER,
    ROLE_ECX_ADMIN,
    ROLE_ECX_USER,
    ROLE_CMS_ADMIN,
    ROLE_CMS_USER,
    ROLE_AMS_ADMIN,
    ROLE_AMS_MANAGER,
    ROLE_AMS_TEAM_LEADER,

    ROLE_AMS_MEMBER,
    ROLE_AMS_AUDITEE,


    ROLE_SMS_ADMIN,
    ROLE_CIST_ADMIN,
    ROLE_SMS_USER,
    ROLE_ICMS_BANKING_OPERATION,

    ROLE_ICMS_DISTRICT_DIRECTOR,


}
